### PR TITLE
added: serialize in asScalar

### PR DESCRIPTION
**Pull request by ZirgVoice**
added serialize to asScalar function and fix swift 6 warnings

I encountered the bug described [here](https://github.com/GraphQLSwift/GraphQL/issues/157). This pull request fixes it.

### CODE REVIEW

**Review by d-exclaimation — DISMISSED** [review]

**Comment by d-exclaimation** [comment]
Looks good to me, seemed like the pipeline is failing because the version of Swift 5 is too old, can you swap that out from 5.6 to 5.10 or just remove that one.

**Comment by d-exclaimation** [comment]
> Looks good to me, seemed like the pipeline is failing because the version of Swift 5 is too old, can you swap that out from 5.6 to 5.10 or just remove that one.

I made those changes, all is required now is to rebase/merge main to this PR

**Review by d-exclaimation — DISMISSED** [review]

**Comment by ZirgVoice** [comment]
Something weird is going on, maybe you can figure out why it doesn't recognize it as a string

Bildschirmfoto 2024-11-17 um 11 20 06

**Comment by d-exclaimation** [comment]
Weird, I can investigate later but last I checked it runs fine on main.

I'll double check as well what's up with ID

**Comment by ZirgVoice** [comment]
> I'll double check as well what's up with ID

I fixed the type cast. Not sure if it's the right fix, but it works.

>Weird, I can investigate later but last I checked it runs fine on main.

I still haven't figured this out, maybe the error only appears on MacOS

**Review by d-exclaimation — DISMISSED** [review]

**Review by d-exclaimation — APPROVED** [review]

**Comment by ZirgVoice** [comment]
@d-exclaimation ping on this

**Comment by d-exclaimation** [comment]
Should be part of [`v1.4.1`](https://github.com/d-exclaimation/pioneer/releases/tag/1.4.1)

**Pull request merged**
